version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "8m"
    restart: always
    networks:
      - load-balancing-network

  sample-rate-limiting-app:
    image: csonyu/sample-rate-limiting-app:1.0.0
    expose:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "144m"
    restart: always
    networks:
      - load-balancing-network

networks:
  load-balancing-network:
    name: load-balancing-network
    driver: bridge